// ═══════════════════════════════════════════════════
// HeadBand! — DON'T SAY IT!! Seed Generator
// Parses "DONT_SAY_IT_Full_Deck_2000 words.xlsx" (sheet3 "Full Deck":
// # | TARGET | FORBIDDEN 1-6 | CATEGORY) → db/seed-taboo.sql
//
// Usage:  node db/seed-taboo.mjs
// No dependencies — reads the xlsx zip container directly.
// ═══════════════════════════════════════════════════
import { readFileSync, writeFileSync } from 'node:fs';
import { inflateRawSync } from 'node:zlib';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const XLSX_PATH = join(ROOT, 'DONT_SAY_IT_Full_Deck_2000 words.xlsx');
const OUT_PATH = join(ROOT, 'db', 'seed-taboo.sql');

function zipEntries(buf) {
  const eocd = buf.lastIndexOf(Buffer.from('PK\x05\x06', 'latin1'));
  if (eocd < 0) throw new Error('Not a zip file (EOCD missing)');
  let p = buf.readUInt32LE(eocd + 16);
  const entries = {};
  while (p + 4 <= buf.length && buf.readUInt32LE(p) === 0x02014b50) {
    const method = buf.readUInt16LE(p + 10);
    const csize = buf.readUInt32LE(p + 20);
    const nlen = buf.readUInt16LE(p + 28);
    const elen = buf.readUInt16LE(p + 30);
    const clen = buf.readUInt16LE(p + 32);
    const off = buf.readUInt32LE(p + 42);
    entries[buf.toString('utf8', p + 46, p + 46 + nlen)] = { method, csize, off };
    p += 46 + nlen + elen + clen;
  }
  return entries;
}

function readEntry(buf, e) {
  const nlen = buf.readUInt16LE(e.off + 26);
  const elen = buf.readUInt16LE(e.off + 28);
  const d = buf.subarray(e.off + 30 + nlen + elen, e.off + 30 + nlen + elen + e.csize);
  return e.method === 0 ? d : inflateRawSync(d);
}

function decodeXml(s) {
  return s
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(+n));
}

const zip = readFileSync(XLSX_PATH);
const entries = zipEntries(zip);
const sharedXml = readEntry(zip, entries['xl/sharedStrings.xml']).toString('utf8');
const sheetXml = readEntry(zip, entries['xl/worksheets/sheet3.xml']).toString('utf8'); // "Full Deck"

const strings = [];
for (const m of sharedXml.matchAll(/<si>(.*?)<\/si>/gs)) strings.push(decodeXml(m[1]));

const cards = [];
const rows = sheetXml.match(/<row[^>]*>.*?<\/row>/gs) ?? [];
rows.forEach((row, ri) => {
  if (ri === 0) return; // header
  const cell = {};
  for (const c of row.matchAll(/<c r="([A-Z]+)\d+"(?:[^>]*?t="(\w+)")?[^>]*>(?:<v>(.*?)<\/v>)?/g)) {
    const [, col, type, raw] = c;
    if (raw === undefined) continue;
    cell[col] = (type === 's' ? strings[+raw] : raw).trim();
  }
  const target = cell.B;
  const forbidden = [cell.C, cell.D, cell.E, cell.F, cell.G, cell.H];
  if (!target || forbidden.some(f => !f)) {
    console.error(`Row ${ri + 1} incomplete — skipped:`, JSON.stringify(cell));
    return;
  }
  cards.push({ target, forbidden, category: cell.I ?? '' });
});

// dedupe targets (unique constraint)
const seen = new Set();
const unique = cards.filter(c => {
  const k = c.target.toLowerCase();
  if (seen.has(k)) return false;
  seen.add(k);
  return true;
});
if (unique.length !== cards.length) console.error(`${cards.length - unique.length} duplicate targets dropped`);

const esc = (s) => s.replace(/'/g, "''");
const arr = (a) => `array[${a.map(f => `'${esc(f)}'`).join(',')}]`;

const lines = [
  '-- Generated by db/seed-taboo.mjs — do not edit by hand.',
  `-- Source: DONT_SAY_IT_Full_Deck_2000 words.xlsx (${new Date().toISOString()})`,
  '',
  'begin;',
  '',
  'delete from public.taboo_cards;',
  '',
];

const BATCH = 250;
for (let i = 0; i < unique.length; i += BATCH) {
  lines.push('insert into public.taboo_cards (target, forbidden, category) values');
  lines.push(unique.slice(i, i + BATCH)
    .map(c => `  ('${esc(c.target)}', ${arr(c.forbidden)}, '${esc(c.category)}')`)
    .join(',\n') + ';');
  lines.push('');
}

lines.push('commit;');
lines.push('');
writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');

console.log(`Cards:  ${unique.length}`);
console.log(`Sample: ${unique[0].target} → ${unique[0].forbidden.join(', ')}`);
console.log(`Wrote:  ${OUT_PATH}`);
