-- ═══════════════════════════════════════════════════
-- HeadBand! — DON'T SAY IT!! (Mode 3) Schema
-- Run in: Supabase Dashboard → SQL Editor → New Query
-- Run BEFORE seed-taboo.sql. Requires supabase-decks.sql already applied.
-- ═══════════════════════════════════════════════════

-- 1. TABOO CARDS (target word + 6 forbidden words per card)
create table if not exists public.taboo_cards (
  id        bigint generated always as identity primary key,
  target    text not null,
  forbidden text[] not null check (array_length(forbidden, 1) = 6),
  category  text not null default '',
  active    boolean not null default true,
  unique (target)
);

create index if not exists taboo_active_idx on public.taboo_cards(id) where active;

-- 2. Deck-catalog row for the mode — carries color/label + updated_at used
--    by clients as the cache-version signal. mode='dontsayit' keeps it out
--    of the Up Top / Charades deck grid.
insert into public.decks (id, name, icon, color, is_premium, mode, sort)
values ('dontsayit', 'Don''t Say It!!', '🚫', '#FF2D55', false, 'dontsayit', 100)
on conflict (id) do update set mode = 'dontsayit', sort = 100;

-- 3. Touch the dontsayit deck row when cards change (cache invalidation)
create or replace function public.touch_taboo_deck()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.decks set updated_at = now() where id = 'dontsayit';
  return coalesce(new, old);
end;
$$;

drop trigger if exists taboo_touch_deck on public.taboo_cards;
create trigger taboo_touch_deck
  after insert or update or delete on public.taboo_cards
  for each row execute procedure public.touch_taboo_deck();

-- 4. RLS — public read (free-deck monetisation model, UI-gated), admin write
alter table public.taboo_cards enable row level security;

drop policy if exists "taboo_read_all" on public.taboo_cards;
create policy "taboo_read_all" on public.taboo_cards for select using (active);

drop policy if exists "taboo_admin_write" on public.taboo_cards;
create policy "taboo_admin_write" on public.taboo_cards for all
  using ((select auth.jwt()->>'email') = 'usamasiddiqui93@gmail.com')
  with check ((select auth.jwt()->>'email') = 'usamasiddiqui93@gmail.com');

-- 5. Allow the new game style in session logging
alter table public.game_sessions drop constraint if exists game_sessions_game_style_check;
alter table public.game_sessions add constraint game_sessions_game_style_check
  check (game_style in ('headsup', 'charades', 'dontsayit'));

-- Done. Next: run seed-taboo.sql (generated by seed-taboo.mjs).
