-- ═══════════════════════════════════════════════════
-- HeadBand! — Deck Catalog Schema
-- Run in: Supabase Dashboard → SQL Editor → New Query
-- Run BEFORE seed-decks.sql
-- ═══════════════════════════════════════════════════

-- 1. DECKS
create table if not exists public.decks (
  id         text primary key,
  name       text not null,
  icon       text not null default '🎲',
  color      text not null default '#FFD60A',
  is_premium boolean not null default false,
  mode       text not null default 'all',      -- 'all' | future 3rd-mode filter
  sort       int  not null default 0,
  active     boolean not null default true,
  updated_at timestamptz not null default now()
);

-- 2. WORDS
create table if not exists public.words (
  id      bigint generated always as identity primary key,
  deck_id text not null references public.decks(id) on delete cascade,
  text    text not null,
  mode    text not null default 'all',
  active  boolean not null default true,
  unique (deck_id, text)
);

create index if not exists words_deck_idx on public.words(deck_id) where active;

-- 3. Touch parent deck when words change (cache-version signal for clients)
create or replace function public.touch_deck()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.decks set updated_at = now()
  where id = coalesce(new.deck_id, old.deck_id);
  return coalesce(new, old);
end;
$$;

drop trigger if exists words_touch_deck on public.words;
create trigger words_touch_deck
  after insert or update or delete on public.words
  for each row execute procedure public.touch_deck();

-- 4. ROW LEVEL SECURITY
alter table public.decks enable row level security;
alter table public.words enable row level security;

-- Deck metadata: public read (locked decks must still show 🔒 in the grid)
drop policy if exists "decks_read_all" on public.decks;
create policy "decks_read_all" on public.decks for select using (active);

-- Words v1: public read. Premium gating stays UI-side (matches current
-- localStorage/Xsolla model). Flip to the v2 policy below when you want
-- server-side entitlement gating.
drop policy if exists "words_read_all" on public.words;
create policy "words_read_all" on public.words for select using (active);

-- Words v2 (OPTIONAL — replaces words_read_all; premium decks then require sign-in):
-- drop policy if exists "words_read_all" on public.words;
-- create policy "words_read_gated" on public.words for select using (
--   active and (
--     not (select d.is_premium from public.decks d where d.id = deck_id)
--     or exists (
--       select 1 from public.profiles p
--       where p.id = auth.uid()
--         and p.sub_type <> 'free'
--         and (p.sub_expires_at is null or p.sub_expires_at > now())
--     )
--   )
-- );

-- 5. ADMIN WRITE (deck editor in headband-admin.html)
drop policy if exists "decks_admin_write" on public.decks;
create policy "decks_admin_write" on public.decks for all
  using ((select auth.jwt()->>'email') = 'usamasiddiqui93@gmail.com')
  with check ((select auth.jwt()->>'email') = 'usamasiddiqui93@gmail.com');

drop policy if exists "words_admin_write" on public.words;
create policy "words_admin_write" on public.words for all
  using ((select auth.jwt()->>'email') = 'usamasiddiqui93@gmail.com')
  with check ((select auth.jwt()->>'email') = 'usamasiddiqui93@gmail.com');

-- Done. Next: run seed-decks.sql (generated by seed-decks.mjs).
